# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.TextField(default='', verbose_name='Private Key'),
        ),
    ]
